title: Cours Statistiques et Sciences de Donn√©es
description: |
  Data Scientist - ML Engineer
show_downloads: false
google_analytics: UA-128994988-1
theme: jekyll-theme-architect
github:
  is_project_page: false
email: armel.soubeiga@yahoo.fr
author: Armel SOUBEIGA
url: "https://www.armelsoubeiga.cours.com" 

