title: Cours Statistiques et Sciences de Donn√©es
description: @mail: armel.soubeiga@yahoo.fr
author: Armel SOUBEIGA
show_downloads: false
google_analytics: UA-128994988-1
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
theme: jekyll-theme-architect
