title: Cours Statistiques et Sciences de DonnÃ©es
description: >- Armel SOUBEIGA
                Data Scientist - ML Engineer
                @mail :armel.soubeiga@yahoo.fr
show_downloads: false
theme: jekyll-theme-architect
