name: Cours Statistiques et Sciences de DonnÃ©es
title: 
description: > 
            Armel SOUBEIGA
            Data Scientist - ML Engineer
            @mail :armel.soubeiga@yahoo.fr
show_downloads: false
theme: jekyll-theme-cayman
gems:
  - jekyll-paginate

#Others
markdown: kramdown
